// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: memezis.proto

package memezis

import (
	"context"
	"github.com/cherya/memezis/internal/app/auth"
	"github.com/cherya/memezis/pkg/queue"
	"log"
	"net/http"
	"strconv"
	"sync"

	"github.com/cherya/memezis/internal/app/store"
	e "github.com/cherya/memezis/pkg/errors"
	desc "github.com/cherya/memezis/pkg/memezis"

	"github.com/pkg/errors"
)

func (i *Memezis) AddPost(ctx context.Context, req *desc.AddPostRequest) (*desc.AddPostResponse, error) {
	wg := sync.WaitGroup{}
	errs := make(chan error)
	wgDone := make(chan bool)

	media := make([]*store.Media, 0, len(req.GetMedia()))

	for _, m := range req.GetMedia() {
		if m.GetURL() == "" && m.GetSourceID() == "" {
			return nil, e.WrapC(errors.Errorf("AddPost: empty media %s", m), http.StatusBadRequest)
		}
		if m.GetURL() != "" {
			wg.Add(1)
			// store media forever if it exists
			go func(mr *desc.Media) {
				if !i.fs.IsTempObjExists(m.GetURL()) {
					err := errors.Errorf("AddPost: object %s does not exists", m)
					errs <- e.WrapC(err, http.StatusBadRequest)
				}
				err := i.fs.MakeObjPermanent(m.GetURL())
				if err != nil {
					err = errors.Wrapf(err, "AddPost: can't make object permanent (key=%s)", m)
					errs <- e.WrapC(err, http.StatusInternalServerError)
				}
				wg.Done()
			}(m)
		}

		media = append(media, &store.Media{
			Key:      m.GetURL(),
			Type:     m.GetType(),
			SourceID: m.GetSourceID(),
			SHA1:     m.GetSHA1(),
		})
	}

	go func() {
		wg.Wait()
		close(wgDone)
	}()

	select {
	case <-wgDone:
		break
	case err := <-errs:
		close(errs)
		return nil, err
	}

	client := auth.ClientFromContext(ctx)
	post, err := i.store.AddPost(ctx, media, req.GetTags(), fromProtoTime(req.GetCreatedAt()), client.Name, req.GetAddedBy(), req.GetText())
	if err != nil {
		return nil, e.WrapMC(err, "AddPost: can't save post to store", http.StatusInternalServerError)
	}

	err = i.publishToQueues(post)
	if err != nil {
		log.Println("AddPost: can't add posts to queues", err)
	}

	duplicates, err := i.store.CheckDuplicate(ctx, post.ID)
	if err != nil {
		log.Println("AddPost: can't check duplicates", err)
	}
	return &desc.AddPostResponse{
		ID:         post.ID,
		Duplicates: duplicates,
	}, nil
}

func (i *Memezis) publishToQueues(post *store.Post) error {

	err := i.qm.Push(queue.EverythingQueue, strconv.FormatInt(post.ID, 10))
	if err != nil {
		return errors.Wrapf(err, "publishToQueues: can't add post to queue (queue=%s)", queue.EverythingQueue)
	}

	return nil
}
