// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: memezis.proto

package memezis

import (
	"context"

	"github.com/cherya/memezis/internal/app/store"
	desc "github.com/cherya/memezis/pkg/memezis"
	"github.com/pkg/errors"
)

func (i *Memezis) DownVote(ctx context.Context, req *desc.VoteRequest) (*desc.Vote, error) {
	postID := req.GetPostID()

	vote, err := i.store.DownVote(ctx, postID, req.GetUserID())
	if err != nil {
		if err == store.ErrNotFound {
			return nil, errors.Wrap(err, "post not found")
		}
		return nil, errors.Wrap(err, "can't save vote")
	}

	status, err := i.VotePost(ctx, postID, *vote)
	if err != nil {
		return nil, err
	}

	return &desc.Vote{
		Up:     int64(vote.Up),
		Down:   int64(vote.Down),
		Status: string(status),
	}, nil
}
