// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: memezis.proto

package memezis

import (
	"context"
	desc "github.com/cherya/memezis/pkg/memezis"

	"github.com/pkg/errors"
)


func (i *Memezis) FindDuplicatesByPostID(ctx context.Context, req *desc.FindDuplicatesByPostIDRequest) (*desc.FindDuplicatesByPostIDResponse, error) {
	if req.GetId() == 0 {
		return nil, errors.New("FindDuplicates: id must be greater than 0")
	}

	post, err := i.store.GetPostByID(ctx, req.GetId())
	if err != nil {
		return nil, errors.Wrap(err, "can't get media by ids")
	}

	//TODO: find duplicates for posts with any media amount
	if len(post.Media) > 1 {
		return &desc.FindDuplicatesByPostIDResponse{}, nil
	}

	duplicates, err := i.findDuplicates(ctx, post.Media[0])
	if err != nil {
		return nil, errors.Wrap(err, "error finding media duplicates")
	}

	return &desc.FindDuplicatesByPostIDResponse{
		Complete: duplicates.Complete,
		Likely:   duplicates.Likely,
	}, nil
}