// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: memezis.proto

package memezis

import (
	"context"
	"github.com/cherya/memezis/internal/app/store"
	e "github.com/cherya/memezis/pkg/errors"
	"log"
	"net/http"

	desc "github.com/cherya/memezis/pkg/memezis"
	empty "github.com/golang/protobuf/ptypes/empty"
	"github.com/pkg/errors"
)

func (i *Memezis) GetRandomPost(ctx context.Context, req *empty.Empty) (*desc.Post, error) {
	post, err := i.store.GetRandomPost(ctx)
	if err != nil {
		if errors.Cause(err) == store.ErrNotFound {
			return nil, e.WrapC(err, http.StatusNotFound)
		}
		log.Println("GetRandomPost: can't get post from store", err)
		return nil, errors.Wrap(err, "GetRandomPost: can't get post from store")
	}

	tags, err := i.store.GetTagsByIDs(ctx, post.Tags)
	if err != nil {
		if errors.Cause(err) == store.ErrNotFound {
			tags = []string{}
		}
		log.Println("GetPostByID: can't get tags from store", err)
		return nil, errors.Wrap(err, "GetPostByID: can't get tags from store")
	}

	return toProtoPost(post, tags, i.fs.GetObjAbsoluteURL), nil
}
