// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: memezis.proto

package memezis

import (
	"context"

	desc "github.com/cherya/memezis/pkg/memezis"
	empty "github.com/golang/protobuf/ptypes/empty"
	"github.com/pkg/errors"
)

func (i *Memezis) PublishPost(ctx context.Context, req *desc.PublishPostRequest) (*empty.Empty, error) {
	err := i.store.PublishPost(ctx, req.GetPostID(), fromProtoTime(req.GetPublishedAt()), req.GetPublishedTo(), req.GetURL())
	if err != nil {
		return nil, errors.New("PublishPost: can't mark post published")
	}

	return &empty.Empty{}, nil
}
