// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: memezis.proto

package memezis

import (
	"context"
	"github.com/cherya/memezis/internal/app/store"
	e "github.com/cherya/memezis/pkg/errors"
	desc "github.com/cherya/memezis/pkg/memezis"
	"net/http"
)

func (i *Memezis) UpVote(ctx context.Context, req *desc.VoteRequest) (*desc.Vote, error) {
	postID := req.GetPostID()

	vote, err := i.store.UpVote(ctx, postID, req.GetUserID())
	if err != nil {
		if err == store.ErrNotFound {
			return nil, e.WrapC(err, http.StatusNotFound)
		}
		return nil, e.WrapMC(err, "UpVote: can't save vote", http.StatusInternalServerError)
	}

	status, err := i.VotePost(ctx, postID, *vote)
	if err != nil {
		return nil, err
	}

	return &desc.Vote{
		Up:     int64(vote.Up),
		Down:   int64(vote.Down),
		Status: string(status),
	}, nil
}
